MiniPrject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  url(r'^', include("auctionbuzz.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctionbuzz/models.py
from django.contrib.auth.models import User
from django.db import models
from time import time
from django.utils import timezone

from django.core.validators import RegexValidator

# Create your models here.

def getImage(instance, filename):
    return "auction_system/image_{0}_{1}".format(str(time()),filename)


class Product(models.Model):
    product_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to=getImage)
    category = models.CharField(max_length=100)
    description = models.TextField(max_length=300, default="")
    minimum_price = models.IntegerField(null=True)
    bid_end_date = models.DateField(default=None)
    created = models.DateTimeField(default= timezone.now)
    updated = models.DateTimeField(default= timezone.now)


class Seller(models.Model):
    created = models.DateTimeField(default= timezone.now)
    updated = models.DateTimeField(default= timezone.now)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)




class Bidder(models.Model):
    numeric = RegexValidator(r'^[0-9]*$', 'Only numerics are allowed.')

    created = models.DateTimeField(default= timezone.now)
    updated = models.DateTimeField(default= timezone.now)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    bid_amount = models.CharField(max_length=255, validators=[numeric])


        

templates/auction_system/bidder_list.html
{% extends 'auction_system/bidder_list_base.html' %}
{% load static %}
{% block nav %}
    <li><a href="{% url 'product_detail' product_id %}"><span class="glyphicon glyphicon-arrow-left"
                                                             aria-hidden="true"></span> Back</a></li>
{% endblock %}
{% block content %}
    {% if bidder_list %}
    <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th style="font-size: 30px;font-family: Ascender; color: black">Name</th>
        <th style="font-size: 30px;font-family: Ascender; color: black">Bid Amount</th>
      </tr>
    </thead>
    <tbody>
    {% for bid in bidder_list %}
      <tr>
        <td style="font-size: 29px;font-family: Ascender; color: black">{{ bid.user_name }}</td>
        <td style="font-size: 29px;font-family: Ascender; color: black">{{ bid.bid_amount }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
        {% else %}
            <h2 style="text-align: center; color: black">No bids!!</h2>
    {% endif %}
{% endblock %}

templates/auction_system/bidder_list_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
    <title>Bidder List</title>
    <link rel="shortcut icon" href="media/auctionbuzz/images/icon.png">

    <style type="text/css">
     body {
        padding-bottom: 322px;
        background-repeat: no-repeat;
        background-attachment: fixed;

  position: relative;
}

body::before {
  background: url(/media/auctionbuzz/images/back.jpg) no-repeat center center fixed;
  content: '';
  z-index: -1;
  width: 100%;
  height: 100%;
  position:absolute;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  -webkit-filter: blur(3px);
  -moz-filter: blur(3px);
  -o-filter: blur(3px);
  -ms-filter: blur(3px);
  filter: blur(3px);
}

    .navi{
        background-color:rgba(121, 85, 72, 0.3);


    }
    .home{
        color:black;
        font-size: 40px;
        font-family: Ascender;
        text-decoration:none;
    }
    .home:hover{
        text-decoration: none;
    }
    .about{
        color:black;
        font-size: 40px;
        font-family: Ascender;
        text-decoration:none;
    }
    .about:hover{
        text-decoration: none;
    }
    .login{
        color: black;
        font-size: 40px;
        font-family: Ascender;
        text-decoration:none;
    }
    .login:hover{
        text-decoration: none;
    }
    .us{
        color:black;

        font-size: 30px;
        font-family: Ascender;
        text-decoration:none;


    }
    .us{
        text-decoration: solid;
    }
    .logout{
        color:black;
        font-size: 40px;
        font-family: Ascender;
        text-decoration:none;
    }
    .logout:hover{
        text-decoration: none;
    }
    .reg{
        color: black;
        font-size: 40px;
        font-family: Ascender;
        text-decoration:none;
    }
    .reg:hover{
        text-decoration: none;
    }
    .carousel-inner{
    height:600px !important;

    }
    .im{
      height:110px;
      width:220px;
    }
    .pr1{
      color: skyblue;

        font-size: 15px;
        font-family: Ascender;
        text-decoration:none;

    }
    .pr2{
      color: yellow;
        font-size: 15px;
        font-family: Ascender;
        text-decoration:none;

    }
    .con{

        background-color:rgba(121, 85, 72, 0.3);

    }
    h3{
      color: black;
        font-size: 40px;
        font-family: Ascender;
        text-decoration:none;
    }
    a{
      color:black;
      text-decoration: none;
      font-family: Ascender;
      font-size: 20px;
    }
    a:hover{
        text-decoration: none;
        color: white;
    }
            .profilePicture .img-responsive:hover {
        opacity: 0.2;
    }

    .profilePicture img {
        display: block;
        margin: auto auto 0;
        width: 250px;
        height:250px;
        max-width: 250px;
        max-height: 250px;

    }

    .profilePicture .text {
        position: relative;
        display: block;
        margin-left: auto;
        margin-right: auto;
        margin-top: 0;
        text-align: center;
        visibility: hidden;
        width: 250px;
        height: 30px;
        font-family:  Ascender;
    }
    .profilePicture:hover .text {
        visibility:visible;
    }
    </style>
</head>
<body>
      <!-- <div class="container-fluid">
            <div class="row">
                <div class="col4">
                    <img src="/media/auctionbuzz/images/l2.png" class="img-fluid">

                </div>
                <div class="col2 home">
                        <a class="home" href="two.html">Home </a>
                    </div>
                    <div class="col2 about">
                            <a class="about" href="">  About</a></a>
                        </div>
                        <div class="col2 login">
                                <a class="login" href="">  Login</a></a>
                                </div>

                                <div class="col2 reg">
                                        <a class="reg" href="">  Registration</a></a>
                                        </div>

            </div>

        </div>-->
        <nav class="navbar navbar-dark primary-color navi">
            <a class="navbar-brand" href="#">
              <img src="/media/auctionbuzz/images/l2.jpg" height="50" alt="mdb logo">
            </a>
            <a class="navbar-brand" href="#">
           <a href="{% url 'home' %}" class="home" >Home </a>
            </a>
            <a class="navbar-brand" href="#">
           <a class="about" href="">About</a></a>

        <a href="{% url 'product_detail' product_id %}" style="font-size: 40px"><span class="glyphicon glyphicon-arrow-left"
                                                             aria-hidden="true"></span> Back</a>

           {% if user.is_authenticated %}
                   <a class="navbar-brand" href="#"></a>
                   <a href="{% url 'logout' %}" class="logout">Logout</a>
                   <p class="us">Hello <br>{{user.username}}</p>

           {% else %}
                   <a class="navbar-brand" href="#">
                   <a href="{% url 'login' %}" class="login">Login</a></a>
                   <a class="navbar-brand" href="#">
                   <a href="{% url 'registration' %}" class="reg">Registration</a></a>
           {% endif %}

          </nav>
         <br>
          <br>
          <br>
    <!--      <div class="container">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">

                        <ol class="carousel-indicators">
                          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                          <li data-target="#myCarousel" data-slide-to="1"></li>
                          <li data-target="#myCarousel" data-slide-to="2"></li>
                        </ol>


                        <div class="carousel-inner">
                          <div class="item active">
                            <img src= '/media/auctionbuzz/images/g1.jpg' alt="Los Angeles">
                          </div>

                          <div class="item">
                            <img src='/media/auctionbuzz/images/g2.jpg' alt="Chicago">
                          </div>

                          <div class="item">
                            <img src='/media/auctionbuzz/images/g3.jpg' alt="New York">
                          </div>
                        </div>


                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                          <span class="glyphicon glyphicon-chevron-left"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">
                          <span class="glyphicon glyphicon-chevron-right"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      </div>



        </div>


    -->

<div class="container">
    {% block content %}
    {% endblock %}
</div>



     <script src="js/jquery.min.js"></script>
     <script src="js/bootstrap.js"> </script>
</body>

</html>

templates/auction_system/college_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ status }}
</body>
</html>

templates/auction_system/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
    <title>AuctionBuzz</title>
    <link rel="shortcut icon" href="media/auctionbuzz/images/icon.png">

    <style type="text/css">
     body {
        padding-bottom: 720px;
        background-repeat: no-repeat;
        background-attachment: fixed;

  position: relative;
}

body::before {
  background: url(/media/auctionbuzz/images/back.jpg) no-repeat center center fixed;
  content: '';
  z-index: -1;
  width: 100%;
  height: 100%;
  position:absolute;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  -webkit-filter: blur(3px);
  -moz-filter: blur(3px);
  -o-filter: blur(3px);
  -ms-filter: blur(3px);
  filter: blur(3px);
}

    .navi{
        background-color:rgba(121, 85, 72, 0.3);
        width: 100%;
        

    }
    .home{
        color: black;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .home:hover{
        text-decoration: none;
    }
    .about{
        color:black;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .about:hover{
        text-decoration: none;
    }
    .login{
        color: black;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .login:hover{
        text-decoration: none;
    }
    .us{
        color: black;

        font-size: 30px;
        font-family:Ascender;
        text-decoration:none;


    }
    .us{
        text-decoration: solid;
    }
    .logout{
        color:black ;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .logout:hover{
        text-decoration: none;
    }
    .reg{
        color: black;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .reg:hover{
        text-decoration: none;
    }
    .carousel-inner{
    height:600px !important;

    }
    .im{
      height:110px;
      width:220px;
    }
    .pr1{
      color: skyblue;

        font-size: 15px;
        font-family:Ascender;
        text-decoration:none;

    }
    .pr2{
      color: yellow;
        font-size: 15px;
        font-family:Ascender;
        text-decoration:none;

    }
    .con{

        background-color:rgba(121, 85, 72, 0.3);

    }
    h3{
      color: darkgreen;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    a{
      color:skyblue;
      text-decoration: none;
      font-family:Ascender;
      font-size: 20px;
    }
    a:hover{
        text-decoration: none;
        color: white;
    }
            .profilePicture .img-responsive:hover {
        opacity: 0.2; 
    }

    .profilePicture img {
        display: block;
        margin: auto auto 0;
        width: 250px;
        height:250px;
        max-width: 250px;
        max-height: 250px;

    }

    .profilePicture .text {
        position: relative;
        display: block;
        margin-left: auto;
        margin-right: auto;
        margin-top: 0;
        text-align: center;
        visibility: hidden;
        width: 250px;
        height: 30px;
        font-family: "Maiandra GD", serif;
    }
    .profilePicture:hover .text {
        visibility:visible;
    }
    
    .custom-centered{
   margin:0 auto;
   width:300px;
   font-family:Ascender;
   color: darkgreen;
}
    </style>
</head>
<body>
      <!-- <div class="container-fluid">
            <div class="row">
                <div class="col4">
                    <img src="/media/auctionbuzz/images/l2.png" class="img-fluid">

                </div>
                <div class="col2 home">
                        <a class="home" href="two.html">Home </a>
                    </div>
                    <div class="col2 about">
                            <a class="about" href="">  About</a></a>
                        </div>
                        <div class="col2 login">
                                <a class="login" href="">  Login</a></a>
                                </div>

                                <div class="col2 reg">
                                        <a class="reg" href="">  Registration</a></a>
                                        </div>

            </div>

        </div>-->
        <nav class="navbar navbar-dark primary-color navi">
            <a class="navbar-brand" href="#">
              <img src="/media/auctionbuzz/images/l2.jpg" height="50" alt="mdb logo">
            </a>
            <a class="navbar-brand" href="#">
           <a href="{% url 'home' %}" class="home" >Home </a>
            </a>
            <a class="navbar-brand" href="#">
           <a class="about" href="">About</a></a>
           {% if user.is_authenticated %}
                   <a class="navbar-brand" href="#"></a>
                   <a href="{% url 'logout' %}" class="logout">Logout</a>
                   <p class="us">Hello <br>{{user.username}}</p>

           {% else %}
                   <a class="navbar-brand" href="#">
                   <a href="{% url 'login' %}" class="login">Login</a></a>
                   <a class="navbar-brand" href="#">
                   <a href="{% url 'registration' %}" class="reg">Registration</a></a>
           {% endif %}

          </nav>
          
         <br>
          <br>
          <br>
          
            <div class="col-lg-1">
             <form role="form" class="custom-centered" >
                <div class="form-group">
                </div>
                <div class="form-group">
                    <div class="card text-center">
                        <div class="card-header">
                          CaroBar
                        </div>
                        <div class="card-body">
                          <h5 class="card-title">Digital Marketplace</h5>
                          <p class="card-text">Carobar is a leading digital marketplace and solutions provider for 
                              the automotive industry that connects car shoppers with sellers.
                        </p>
                        </div>
                      </div>
                </div>
            </form>
            </div>

      {% if user.is_authenticated %}
      <div class="container">
        <h3>ANNOUNCEMENT</h3>
      <div class="row con">
        <div class="container">
          <div class="row con">
            <div class="col-4"></div>
            <div class="col-4">
            <a href="{% url 'add_product' %}">I Want To Announce</a>
            </div>
            <div class="col-4"></div>
        </div>
        </div>
          {% endif %}



      </div>
    </div>

      {% if user.is_authenticated %}
          {% block content %}
                <br><br>
                <div id="gallery">
                    {% for product in product_list %}
                        <div class="col-md-3 col-sm-4">
                            <div class="profilePicture">
                                <a href="{% url 'product_detail' product.id %}">
                                    <img src="{{ product.image.url }}" class="img-responsive" alt="Image"></a>
                                <h3 class="text" style="background-color: black; color: white"><b>{{ product.product_name }}</b></h3>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endblock %}
      {% endif %}


     <script src="js/jquery.min.js"></script>
     <script src="js/bootstrap.js"> </script>
</body>

</html>

templates/auction_system/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Login</title>
    <link rel="shortcut icon" href="media/auctionbuzz/images/icon.png">

    <style type="text/css">
        body {
        padding-bottom: 205px;
        background-repeat: no-repeat;
        background-attachment: fixed;

  position: relative;
}

body::before {
  background: url(/media/auctionbuzz/images/back.jpg) no-repeat center center fixed;
  content: '';
  z-index: -1;
  width: 100%;
  height: 100%;
  position:absolute;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  -webkit-filter: blur(3px);
  -moz-filter: blur(3px);
  -o-filter: blur(3px);
  -ms-filter: blur(3px);
  filter: blur(3px);
}   a{
        text-decoration: none;
    }


    .navi{
        background-color:rgba(121, 85, 72, 0.3);


    }
    .home{
        color: black;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .home:hover{
        text-decoration: none;
    }
    .about{
        color:black;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .about:hover{
        text-decoration: none;
    }
    .login{
        color: black;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .login:hover{
        text-decoration: none;
    }
    .reg{
        color:black;
        font-size: 40px;
        font-family:Ascender;
        text-decoration:none;
    }
    .reg:hover{
        text-decoration: none;
    }
    .second{
        background-color:rgba(121, 85, 72, 0.3);
        border: 1px solid #fff;
        padding: 50px 60px;
        box-shadow:rgba(121, 85, 72, 0.3) ;


    }
    .log{
        color: black;
        font-size: 20px;
        font-family: Ascender;

    }
    input{
        color: blue;

        font-size: 20px;
    }
    .uname{
        background-color: darkgrey;
        color: rgb(15, 69, 105);
    }
    .fo{
        color:rgb(255, 252, 246);
        font-size: 20px;
        font-family: Ascender;

    }
    .do{
        color: rgb(10, 10, 10);
        font-size: 20px;
        border-radius: 10%;
        border:solid;
        font-family: Ascender;


    }
    .do:hover{
        background-color: green;
    }
    .me{
        color: red;
        font-family: Ascender;


    }
    a:hover{
        text-decoration: none;
        color: white;
    }
    </style>
</head>
<body>
        <nav class="navbar navbar-dark primary-color navi">
                <a class="navbar-brand" href="#">
                  <img src="/media/auctionbuzz/images/l2.jpg" height="50" alt="mdb logo">
                </a>
                <a class="navbar-brand" href="#">
               <a href="{% url 'home' %}" class="home" >Home </a>
                </a>
                <a class="navbar-brand" href="#">
               <a class="about" href="">About</a></a>
               <a class="navbar-brand" href="#">
               <a href="{% url 'login' %}" class="login">Login</a></a>
               <a class="navbar-brand" href="#">
               <a href="{% url 'registration' %}" class="reg">Registration</a></a>

              </nav>
              <br>
              <br>
              <br>
             <div class="container">
                  <div class="row second">

                  <div class="col-4 log">
                  </div>
                  <div class="col-4 log">
                        <form action="" method="POST">
                                {% csrf_token %}

                                <div class="form-group fo" class="do">
                                <fieldset class="form-group">
                                    <div class="form-group">
                                        <label for="username">Username</label><br>
                                        <input type="text" class="form-control"  name="username" placeholder="username" class="uname" required/>
                                      </div>
                                      <div class="form-group">
                                        <label for="password">Password</label><br>
                                        <input type="password" class="form-control"name="password" placeholder="password" class="uname" required/>
                                      </div>
                                  <!--  <a class="uuname">Username:</a><br>
                                    <input type="text" name="username" placeholder="username" class="uname" required/><br>

                                    <a class="uupw">Password:</a><br>
                                    <input type="password" name="password" placeholder="password" class="uname" required/><br>-->
                                </fieldset>

                                </div>
                                <div class="form-group ">
                                    <button type="submit" class="btn btn-success btn-block" class="do">LOGIN</button><br>
                                       <!-- <input type="submit" value="LOGIN" class="do"/><br>-->
                                </div>

                                <a href="{% url 'registration' %}">Add New Account</a>
                                <div>
                                        {% for message in messages %}
                                        <h3 class="me">{{message}}</h3>
                                        {% endfor %}
                                    </div>

    <div class="col-4 log">
        </div>
    </div>
    </div>
     <script src="js/jquery.min.js"></script>
     <script src="js/bootstrap.js"> </script>
</body>

</html>

templates/auction_system/product_confirm_delete.html
{% extends 'auction_system/product_confirm_delete_base.html' %}
{% load static %}

{% block content %}
<h2>Delete List</h2>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete?</p>
    <button class="btn btn-lg btn-block" type="submit" style="background-color: black; color: white; width:100px">Confirm</button>
</form>
{% endblock %}

templates/auction_system/product_form.html
{% extends 'auction_system/product_form_base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_bid_end_date").datepicker({
                minDate: 0,
                maxDate: 200,
            });

        });
    </script>
{% endblock %}
{% block content %}
    <form class="form-signin" method="post" action="" enctype="multipart/form-data" style="font-family: Comic Sans MS, serif; margin: auto">{% csrf_token %}
        <h2 class="form-signin-heading"></h2>

            <div class="form-group fo">
        <fieldset class="form-group">
        <table style="font-family: Ascender, serif;font-size: 15px;color: white">
            {% for field in form %}
                {% if field.help_text %}
                    <tr style="color: black;">
                        <td colspan="4">{{ field.help_text }}</td>
                    </tr>
                    <tr class="blank_row">

                    </tr>
                {% endif %}
                <tr>
                    <td>{{ field.label_tag }}</td>
                    <td>{{ field }}</td>
                </tr>
                <tr class="blank_row">

                </tr>
                {% if field.errors %}
                    <tr style="color: red">
                        <td colspan="4">{{ field.errors }}</td>
                    </tr>
                    <tr class="blank_row">

                    </tr>
                {% endif %}

            {% endfor %}
        </table>
        <button class="btn btn-lg btn-block" type="submit" style="background-color: black; color: white">Submit
        </button>
        <br>
        </fieldset>
            </div>
    </form>
    <br><br><br>
{% endblock %}

templates/auction_system/product_list.html
{% extends 'auction_system/productlist_base.html' %}
{% load static %}
{% block head %}
    <style>
        .profilePicture .img-responsive:hover {
            opacity: 0.2;
        }

        .profilePicture img {
            display: block;
            margin: auto auto 0;
            width: 250px;
            height:250px;
            max-width: 250px;
            max-height: 250px;

        }

        .profilePicture .text {
            position: relative;
            display: block;
            margin-left: auto;
            margin-right: auto;
            margin-top: 0;
            text-align: center;
            visibility: hidden;
            width: 250px;
            height: 55px;
            font-family: Ascender;
        }
        .profilePicture:hover .text {
            visibility:visible;
        }
    </style>
{% endblock %}
{% block content %}
    <br><br>
    <div id="gallery">
        {% for product in product_list %}
            <div class="col-md-3 col-sm-4">
                <div class="profilePicture">
                    <a href="{% url 'product_detail' product.id %}">
                        <img src="{{ product.image.url }}" class="img-responsive" alt="Image"></a>
                    <h3 class="text" style="background-color: black; color: white"><b>{{ product.product_name }}</b></h3>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}